# Generated by Django 3.1.4 on 2020-12-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sotrudnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_f', models.CharField(max_length=200)),
                ('name_i', models.CharField(max_length=200)),
                ('name_o', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('attestat_form', models.CharField(max_length=200)),
            ],
        ),
    ]
